=== bernardbdas/wsd-lab4/users.xsd
<?xml version="1.0"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="citation_generator">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="cid"/>
                            <xs:element type="xs:string" name="name"/>
                            <xs:element type="xs:integer" name="age"/>
                            <xs:element type="xs:string" name="nationality"/>
                            <xs:element type="xs:string" name="designation"/>
                            <xs:element type="xs:string" name="email"/>
                            <xs:element type="xs:long" name="contact"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="name">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="3"/>
                <xs:maxLength value="25"/>
                <xs:whiteSpace value="preserve"/>
                <xs:pattern value="([A-Za-z]){25}"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="age">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:maxExclusive value="110"/>
                <xs:minInclusive value="0"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="nationality">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="3"/>
                <xs:maxLength value="20"/>
                <xs:pattern value="([A-Za-z]){20}"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="designation">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="5"/>
                <xs:maxLength value="20"/>
                <xs:whiteSpace value="preserve"/>
                <xs:pattern value="([A-Za-z]){20}"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="email">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="12"/>
                <xs:maxLength value="40"/>
                <xs:pattern value="([a-z@]*)"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:simpleType name="contact">
        <xs:restriction base="xs:string">
            <xs:pattern value="([0-9]){10}"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== bernardbdas/wsd-lab4/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="xsl" href="users.xsl"?>

<citation_generator xmlns="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="users.xsd">

    <user>
        <cid>C01</cid>
        <name>Person A</name>
        <age>23</age>
        <nationality>Portugal</nationality>
        <designation>Law Enthusiast</designation>
        <email>person_a@cdpl.com</email>
        <contact>9832743245</contact>
    </user>
    <user>
        <cid>C02</cid>
        <name>Person B</name>
        <age>34</age>
        <nationality>United States</nationality>
        <designation>Research Scholar</designation>
        <email>person_b@cdpl.com</email>
        <contact>3289903449</contact>
    </user>
    <user>
        <cid>C03</cid>
        <name>Person C</name>
        <age>17</age>
        <nationality>Ghana</nationality>
        <designation>Law Enthusiast</designation>
        <email>person_c@cdpl.com</email>
        <contact>0923762856</contact>
    </user>
    <user>
        <cid>C04</cid>
        <name>Person D</name>
        <age>45</age>
        <nationality>Singapore</nationality>
        <designation>Law Enthusiast</designation>
        <email>person_d@cdpl.com</email>
        <contact>7835345344</contact>
    </user>
    <user>
        <cid>C05</cid>
        <name>Person E</name>
        <age>53</age>
        <nationality>Japan</nationality>
        <designation>Lawyer</designation>
        <email>person_e@cdpl.com</email>
        <contact>4764937484</contact>
    </user>
    <user>
        <cid>C06</cid>
        <name>Person F</name>
        <age>65</age>
        <nationality>Finland</nationality>
        <designation>Barrister</designation>
        <email>person_f@cdpl.com</email>
        <contact>3480273846</contact>
    </user>
    <user>
        <cid>C07</cid>
        <name>Person G</name>
        <age>34</age>
        <nationality>France</nationality>
        <designation>Law Enthusiast</designation>
        <email>person_g@cdpl.com</email>
        <contact>3749309489</contact>
    </user>
    <user>
        <cid>C08</cid>
        <name>Person H</name>
        <age>32</age>
        <nationality>Australia</nationality>
        <designation>Research Scholar</designation>
        <email>person_h@cdpl.com</email>
        <contact>4674985349</contact>
    </user>
    <user>
        <cid>C09</cid>
        <name>Person I</name>
        <age>39</age>
        <nationality>Denmark</nationality>
        <designation>Research Scholar</designation>
        <email>person_i@cdpl.com</email>
        <contact>4578203847</contact>
    </user>
    <user>
        <cid>C10</cid>
        <name>Person J</name>
        <age>44</age>
        <nationality>India</nationality>
        <designation>Lawyer</designation>
        <email>person_j@cdpl.com</email>
        <contact>3647839039</contact>
    </user>
</citation_generator>
